apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: PROJECT_NAME
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/default/nodejs-example
